services:
  # Spec-kit environment for specification generation
  speckit:
    build:
      context: .
      dockerfile: Dockerfile.speckit
    container_name: speckit-dev
    volumes:
      - .:/workspace
      - ~/.gitconfig:/home/appuser/.gitconfig:ro
    working_dir: /workspace
    user: '${UID:-1000}:${GID:-1000}'
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
      - USER=appuser
    command: /bin/bash
