#!/bin/bash

# Script to help with spec-kit workflow

echo "======================================"
echo "CRUDkit Spec-Kit Workflow Guide"
echo "======================================"
echo ""
echo "IMPORTANT: Spec-Kit uses TWO different command systems:"
echo ""
echo "1. CLI Tool (specify) - ONLY for project initialization:"
echo "   specify init crudkit --here --ai claude"
echo ""
echo "2. AI Assistant Commands - Used in Claude/Copilot chat:"
echo "   /specify - Generate specification from requirements"
echo "   /plan    - Create technical implementation plan"
echo "   /tasks   - Break down plan into actionable tasks"
echo ""

# Check if spec-kit project is initialized
if [ ! -f ".specify/config.json" ]; then
    echo "---------------------------------------"
    echo "Spec-kit project not initialized."
    echo ""
    echo "To initialize (optional, one-time setup):"
    echo "   docker compose exec speckit specify init crudkit --here --ai claude"
    echo ""
fi

echo "---------------------------------------"
echo "WORKFLOW:"
echo ""
echo "1. In your AI assistant (Claude, Copilot, etc.), use:"
echo "   /specify Create specification based on constitution.md"
echo ""
echo "2. Save the generated spec to: spec.md"
echo ""
echo "3. Then use:"
echo "   /plan Generate technical plan from spec.md"
echo ""
echo "4. Finally use:"
echo "   /tasks Break down plan into actionable tasks"
echo ""
echo "The spec.md contains:"
echo "- Complete system architecture"
echo "- Sprint requirements and priorities"
echo "- Technical implementation details"
echo "- Testing strategies"
echo "- Security requirements"
echo ""
echo "Remember: /specify, /plan, /tasks are AI CHAT commands, NOT bash commands!"