// Auto-generated by detect-project.js
// DO NOT EDIT MANUALLY - This file is regenerated on each build

export const projectConfig = {
  "projectName": "CRUDkit",
  "projectOwner": "TortoiseWolfe",
  "projectHost": "github.com",
  "projectUrl": "https://github.com/TortoiseWolfe/CRUDkit",
  "basePath": "",
  "isGitHub": true,
  "detectionSource": "git",
  "generatedAt": "2025-09-18T13:59:11.062Z"
} as const;

export type ProjectConfig = typeof projectConfig;
